name: 'Setup release'
description: 'Setup to release outputs based on platform'

inputs:
  platform:
    description: 'GitHub runner platform'
    required: true
  app_name:
    description: 'Application binary name'
    required: true
  build_profile:
    description: 'Rust build profile'
    required: false
    default: 'release'

runs:
  using: 'composite'
  steps:
    # Since upload-artifact cannot include empty directories, put the files in
    - name: Ensure ./build/interface/ is retained
      shell: bash
      run: |
        mkdir -p ./build/assets
        mkdir -p ./build/interface
        touch ./build/interface/.keep

    - name: Compress outputs (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Move-Item -Path ./target/${{ inputs.build_profile }}/${{ inputs.app_name }}.exe -Destination './build'
        Move-Item -Force -Path ./resource/assets -Destination ./build

    - name: Compress outputs (macOS/Linux)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        mv ./target/${{ inputs.build_profile }}/${{ inputs.app_name }} ./build
        mv ./resource/assets ./build
