[workspace.package]
version = "0.1.0"
description = ""
categories = ["games", "parsing"]
authors = ["SARDONYX-sard"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/SARDONYX-sard/d-merge"
readme = "README.md"
edition = "2021"
rust-version = "1.87"

[workspace]
members = [
  "core/json_patch",
  "core/mod_info",
  "core/nemesis_merge",
  "core/nemesis_xml",
  "core/node_expr",
  "core/serde_hkx_for_gui",
  "core/skyrim_anim_parser",
  "core/skyrim_crc",
  "core/skyrim_data_dir",
  "core/tracing_rotation",
  "ffi/javascript/node",
  "ffi/python",
  "gui/app_egui",
  "gui/backend/tauri",
]
resolver = "2"

[workspace.dependencies]
dashmap = { version = "6.1.0" }
educe = { version = "0.6.0" }
futures = { version = "0.3.31" }
glob = "0.3.3"
indexmap = { version = "2.11.4", features = ["rayon"] }
jwalk = { version = "0.8.1" }
napi = { version = "3.2.4" } # Node.js FFI
napi-derive = "3.2.4"
once_cell = "1.21.3"
phf = "0.13.1"
rayon = "1.11.0"
rmp-serde = "1.3.0" # message pack binary serde
serde = { version = "1.0.228", features = ["derive"] } # Implement (De)Serialize
serde_json = "1.0.145" # gui: To avoid generate_context error.
serde_repr = "0.1.20" # C like Serialize enum into numbers.(Using progress reporting)
simd-json = "0.16.0"
snafu = "0.8.9"
tokio = { version = "1.47.1", features = [ "fs", "rt-multi-thread" ] } # Async runtime
tracing = { version = "0.1.41" } # logger
tracing-subscriber = "0.3.20"
winnow = { version = "0.7.13", features = ["simd"] }

diff = { git = "https://github.com/SARDONYX-forks/d-merge-serde-hkx", rev = "9500fa9", default-features = false }
havok_classes = { git = "https://github.com/SARDONYX-forks/d-merge-serde-hkx", rev = "9500fa9", default-features = false, features = [ "ignore_duplicates" ] }
havok_types = { git = "https://github.com/SARDONYX-forks/d-merge-serde-hkx", rev = "9500fa9", default-features = false }
serde_hkx = { git = "https://github.com/SARDONYX-forks/d-merge-serde-hkx", rev = "9500fa9", default-features = false }
serde_hkx_features = { git = "https://github.com/SARDONYX-forks/d-merge-serde-hkx", rev = "9500fa9", default-features = false }

# dev-dependencies
pretty_assertions = "1.4.1"                                  # Color diff assertion
quick_tracing = { version = "0.1.5", features = ["derive"] } # Easy logging

# workspace members
json_patch = { path = "./core/json_patch" }
mod_info = { path = "./core/mod_info" }
nemesis_merge = { path = "./core/nemesis_merge" }
nemesis_xml = { path = "./core/nemesis_xml" }
node_expr = { path = "./core/node_expr" }
serde_hkx_for_gui = { path= "./core/serde_hkx_for_gui" }
skyrim_anim_parser = { path = "./core/skyrim_anim_parser" }
skyrim_crc = { path = "./core/skyrim_crc" }
skyrim_data_dir = { path = "./core/skyrim_data_dir" }
tracing_rotation = { path= "./core/tracing_rotation" }

# NOTE: Set this to lto because there is a part of CI that assumes release dir, and use lto only when the tag is typed.
[profile.release]
# NOTE: Optimizing to the limit reduces the size of the binary, but for some reason,
# the second async fn cannot be executed, resulting in an error, so it is turned off.
# codegen-units = 1
debug = false
# lto = true
opt-level = 3
# panic = 'abort'
strip = true

# Use release mode during development to prevent `serde-hkx` stack overflow
# - ref: https://doc.rust-lang.org/cargo/reference/profiles.html#release
[profile.release-no-lto]
inherits = "dev"
opt-level = 3
debug = false
strip = "none"
debug-assertions = false
overflow-checks = false
lto = false
panic = 'unwind'
incremental = false
codegen-units = 16
rpath = false

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }

# allow list
derive_partial_eq_without_eq = "allow"
future_not_send = "allow"
multiple_crate_versions = "allow"
option_if_let_else = "allow"
pub_with_shorthand = "allow"
redundant_pub_crate = "allow"
result_large_err = "allow"

# custom deny list
char_lit_as_u8 = "deny"
checked_conversions = "deny"
clone_on_ref_ptr = "deny"
cognitive_complexity = "deny"
debug_assert_with_mut_call = "deny"
disallowed_script_idents = "deny"
doc_link_with_quotes = "deny"
empty_enum = "deny"
empty_line_after_outer_attr = "deny"
empty_structs_with_brackets = "deny"
expect_used = "deny"
expl_impl_clone_on_copy = "deny"
explicit_deref_methods = "deny"
explicit_into_iter_loop = "deny"
fallible_impl_from = "deny"
filetype_is_file = "deny"
filter_map_next = "deny"
flat_map_option = "deny"
float_cmp = "deny"
float_cmp_const = "deny"
float_equality_without_abs = "deny"
fn_params_excessive_bools = "deny"
fn_to_numeric_cast_any = "deny"
from_iter_instead_of_collect = "deny"
if_let_mutex = "deny"
implicit_clone = "deny"
imprecise_flops = "deny"
inefficient_to_string = "deny"
invalid_upcast_comparisons = "deny"
items_after_test_module = "deny"
large_digit_groups = "deny"
large_stack_arrays = "deny"
large_types_passed_by_value = "deny"
let_unit_value = "deny"
linkedlist = "deny"
lossy_float_literal = "deny"
macro_use_imports = "deny"
manual_ok_or = "deny"
map_flatten = "deny"
map_unwrap_or = "deny"
match_same_arms = "deny"
match_wild_err_arm = "deny"
match_wildcard_for_single_variants = "deny"
mem_forget = "deny"
missing_const_for_fn = "deny"
missing_enforced_import_renames = "deny"
missing_errors_doc = "deny"
missing_panics_doc = "deny"
mut_mut = "deny"
mutex_integer = "deny"
needless_borrow = "deny"
needless_continue = "deny"
needless_for_each = "deny"
option_option = "deny"
path_buf_push_overwrite = "deny"
ptr_as_ptr = "deny"
rc_mutex = "deny"
ref_option_ref = "deny"
rest_pat_in_fully_bound_structs = "deny"
same_functions_in_if_condition = "deny"
semicolon_if_nothing_returned = "deny"
single_match_else = "deny"
string_add = "deny"
string_add_assign = "deny"
string_lit_as_bytes = "deny"
string_to_string = "deny"
suspicious_operation_groupings = "deny"
trait_duplication_in_bounds = "deny"
unnested_or_patterns = "deny"
unseparated_literal_suffix = "deny"
unused_self = "deny"
unwrap_in_result = "deny"
unwrap_used = "deny"
useless_let_if_seq = "deny"
useless_transmute = "deny"
verbose_file_reads = "deny"
wildcard_dependencies = "deny"
