//! Generates the SKSE plugin configuration for FNIS alternate animation variables.
//!
//! Computes per-mod base slot values from load order and produces
//! `aa_config.json` consumed by the fnis_aa SKSE plugin at runtime.
use std::borrow::Cow;
use std::path::Path;

use indexmap::IndexMap;
use serde::Serialize;

use crate::behaviors::tasks::fnis::patch_gen::hkx_convert::{AnimIoJob, AnimKind, ConversionJob};
use crate::errors::Error;

// =============================================================================
// Data model
// =============================================================================

/// JSON schema URI embedded in every generated `config.json`.
#[cfg(feature = "schema")]
const SCHEMA_URI: &str =
    "https://raw.githubusercontent.com/SARDONYX-sard/fnis_aa/main/tools/schemars/aa_config.schema.json";

#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub struct AAGroup {
    /// FNIS group name, e.g. `_1hmeqp`.
    ///
    /// Used as the suffix of `FNISaa_<name>` animation variables on the actor.
    pub name: String,

    /// Integer ID matching the `FNIS_aa.<group>()` Papyrus constants (0-53).
    ///
    /// e.g. `_1hmeqp` → `37`, `_dageqp` → `43`.
    #[cfg_attr(feature = "schema", validate(range(min = 0, max = 53)))]
    pub group_id: u64,

    /// First slot index occupied by this mod for this group.
    ///
    /// Slot 0 is always reserved for vanilla. Custom slots start at 1 and are
    /// assigned contiguously in mod load order:
    /// ```text
    /// slot 0        vanilla
    /// slot 1..N     mod A  (base=1, slot_count=N)
    /// slot N+1..M   mod B  (base=N+1, slot_count=M-N)
    /// ```
    pub base: u64,

    /// Number of animation styles registered by this mod for this group.
    ///
    /// Determines how many slots this mod occupies starting from `base`.
    pub slot_count: u64,
}

#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub struct AAMod {
    /// 3-character mod prefix used by FNIS, e.g. `xpe` for XPMSE.
    ///
    /// Used as the key in `FNIS_aa2::GetAAprefixList()`.
    pub prefix: String,

    /// Full mod name, e.g. `XPMSE`.
    ///
    /// Used for logging and debug output only.
    pub name: String,

    /// Index of this mod in load order, assigned by d_merge.
    ///
    /// Corresponds to the `PP` component of the `PPGGBB` encoded set string.
    pub mod_id: u64,

    /// Animation groups registered by this mod, sorted by `group_id`.
    pub groups: Vec<AAGroup>,
}

/// Root configuration for the `fnis_aa` SKSE plugin.
///
/// Generated by [d_merge](https://github.com/SARDONYX-sard/d_merge) and read
/// at game startup by `fnis_aa.dll`. Replaces the slot layout that the FNIS
/// generator previously baked into `FNIS_aa2.pex`.
///
/// # File location
/// `SKSE/Plugins/fnis_aa/config.json`
///
/// # Example
/// ```json
/// {
///   "$schema": "https://raw.githubusercontent.com/SARDONYX-sard/fnis_aa/main/schema/aa_config.schema.json",
///   "crc": 123456,
///   "fnis_version": "V07.06.00.0",
///   "mods": [
///     {
///       "prefix": "xpe",
///       "name": "XPMSE",
///       "mod_id": 0,
///       "groups": [
///         { "name": "_1hmeqp", "group_id": 37, "base": 1, "slot_count": 5 }
///       ]
///     }
///   ]
/// }
/// ```
#[derive(Debug, Serialize)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub struct AAConfig {
    /// URI of the JSON schema for this file.
    ///
    /// Always set to the canonical schema URI. Enables schema validation in
    /// editors such as VS Code.
    #[serde(rename = "$schema")]
    #[cfg(feature = "schema")]
    pub schema: Cow<'static, str>,

    /// CRC fingerprint of the current slot layout.
    ///
    /// Computed from mod load order and slot counts. Written to
    /// `FNISaa_crc` on the actor at game load. If the saved value differs,
    /// all animation variables must be re-applied to reflect the new layout.
    pub crc: u32,

    /// FNIS version string returned by `FNISVersionGenerated.get()`.
    ///
    /// e.g. `V07.06.00.0`
    pub fnis_version: Cow<'static, str>,

    /// All mods registered in load order.
    ///
    /// Load order determines `mod_id` assignment and therefore `base` values.
    /// Changing load order produces a different `crc`.
    pub mods: Vec<AAMod>,
}

impl AAConfig {
    /// Creates a new `AAConfig`.
    ///
    /// When the `schema` feature is enabled, the canonical schema URI is
    /// embedded in the output JSON as `$schema`.
    pub fn new(fnis_version: impl Into<Cow<'static, str>>, mods: Vec<AAMod>) -> Self {
        Self {
            #[cfg(feature = "schema")]
            schema: Cow::Borrowed(SCHEMA_URI),
            crc: compute_crc(&mods),
            fnis_version: fnis_version.into(),
            mods,
        }
    }
}

/// Generates the JSON schema for [`AAConfig`] and writes it to
/// `schema/aa_config.schema.json`.
///
/// # Usage
/// ```shell
/// cargo test write_schema --features schema
/// ```
#[cfg(feature = "schema")]
#[test]
fn write_schema() {
    let schema = schemars::schema_for!(AAConfig);
    let json = sonic_rs::to_string_pretty(&schema).unwrap();
    std::fs::create_dir_all("schema").unwrap();
    std::fs::write("schema/aa_config.schema.json", json).unwrap();
}

// =============================================================================
// Group ID constants
// Matches FNIS_aa.<group>() integer constants.
// =============================================================================

fn group_id_from_name(name: &str) -> Option<u64> {
    // NOTE: This must strictly match the constants in the FNIS_aa.psc file within the FNIS script.
    match name {
        "_mtidle" => Some(0),
        "_1hmidle" => Some(1),
        "_2hmidle" => Some(2),
        "_2hwidle" => Some(3),
        "_bowidle" => Some(4),
        "_cbowidle" => Some(5),
        "_h2hidle" => Some(6),
        "_magidle" => Some(7),
        "_sneakidle" => Some(8),
        "_staffidle" => Some(9),
        "_magmt" => Some(16),
        "_magcastmt" => Some(17),
        "_1hmatk" => Some(19),
        "_h2hatk" => Some(33),
        "_h2hatkpow" => Some(34),
        "_magatk" => Some(36),
        "_1hmeqp" => Some(37),
        "_2hweqp" => Some(38),
        "_2hmeqp" => Some(39),
        "_axeeqp" => Some(40),
        "_boweqp" => Some(41),
        "_cboweqp" => Some(42),
        "_dageqp" => Some(43),
        "_h2heqp" => Some(44),
        "_maceqp" => Some(45),
        "_mageqp" => Some(46),
        "_stfeqp" => Some(47),
        "_shout" => Some(48),
        "_magcon" => Some(49),
        "_dw" => Some(50),
        "_jump" => Some(51),
        "_sprint" => Some(52),
        "_shield" => Some(53),
        _ => None,
    }
}

// =============================================================================
// Base computation
// =============================================================================

/// Assigns `base` and `mod_id` for every group across all mods in load order.
/// Slot 0 is always reserved for vanilla; custom slots start at 1.
fn compute_bases(mods: &mut [AAMod]) {
    let mut next_slot = std::collections::HashMap::new();

    for (mod_id, aa_mod) in mods.iter_mut().enumerate() {
        aa_mod.mod_id = mod_id as u64;
        for group in aa_mod.groups.iter_mut() {
            let slot = next_slot.entry(group.group_id).or_insert(1);
            group.base = *slot;
            *slot += group.slot_count;
        }
    }
}

/// CRC fingerprint of the current slot layout.
/// Any change in load order or slot counts invalidates saved Papyrus values.
fn compute_crc(mods: &[AAMod]) -> u32 {
    use std::hash::{Hash, Hasher};
    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    for aa_mod in mods {
        for group in &aa_mod.groups {
            aa_mod.mod_id.hash(&mut hasher);
            group.group_id.hash(&mut hasher);
            group.base.hash(&mut hasher);
        }
    }
    hasher.finish() as u32
}

// =============================================================================
// Output
// =============================================================================

fn write_aa_config(mods: Vec<AAMod>, output_dir: &Path) -> Result<(), Error> {
    let mut mods = mods;
    compute_bases(&mut mods);
    let config = AAConfig::new("V07.06.00.0", mods);

    let path = output_dir.join("SKSE/Plugins/fnis_aa/config.json");
    let json = sonic_rs::to_string_pretty(&config).map_err(|e| Error::JsonError {
        path: path.clone(),
        source: e,
    })?;
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| Error::FailedIo {
            path: parent.to_path_buf(),
            source: e,
        })?;
    }
    std::fs::write(&path, &json).map_err(|e| Error::FailedIo {
        path: path.clone(),
        source: e,
    })?;

    Ok(())
}

// =============================================================================
// Public entry point
// =============================================================================

/// Collects `AAMod` data from a slice of `AnimIoJob` and generates `aa_config.json`.
///
/// Call this once after all `alt_anim_to_oar` jobs have been collected.
/// Load order is preserved via `IndexMap` to ensure a stable CRC.
///
/// Unknown group names are silently skipped.
///
/// # Output path
/// `SKSE/Plugins/fnis_aa/config.json`
pub fn generate_aa_config_from_jobs(jobs: &[AnimIoJob], output_dir: &Path) -> Result<(), Error> {
    // IndexMap preserves insertion order = mod load order, giving a stable CRC.
    let mut aa_mods: IndexMap<String, AAMod> = IndexMap::new();

    for job in jobs {
        let AnimIoJob::Hkx(ConversionJob {
            kind:
                AnimKind::FnisAA {
                    prefix,
                    group_name,
                    slot_count,
                },
            ..
        }) = job
        else {
            continue;
        };

        // Unknown groups produce no valid group_id — skip rather than panic.
        let Some(group_id) = group_id_from_name(group_name) else {
            continue;
        };

        let aa_mod = aa_mods.entry(prefix.clone()).or_insert_with(|| AAMod {
            prefix: prefix.clone(),
            name: prefix.clone(),
            mod_id: 0, // assigned later by compute_bases()
            groups: vec![],
        });

        // Each group appears once per mod regardless of how many animation
        // files reference it.
        if !aa_mod.groups.iter().any(|g| g.name == *group_name) {
            aa_mod.groups.push(AAGroup {
                name: group_name.clone(),
                group_id,
                base: 0, // assigned later by compute_bases()
                slot_count: *slot_count,
            });
        }
    }

    write_aa_config(aa_mods.into_values().collect(), output_dir)
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use super::*;

    fn make_fnis_job(
        prefix: &str,
        group_name: &str,
        slot_index: u64,
        slot_count: u64,
    ) -> AnimIoJob {
        AnimIoJob::Hkx(ConversionJob {
            input_path: PathBuf::from(format!("{prefix}{slot_index}_1hm_equip.hkx")),
            output_path: PathBuf::from("out/1hm_equip.hkx"),
            kind: AnimKind::FnisAA {
                prefix: prefix.to_string(),
                group_name: group_name.to_string(),
                slot_count,
            },
        })
    }

    fn make_standard_job() -> AnimIoJob {
        AnimIoJob::Hkx(ConversionJob {
            input_path: PathBuf::from("idle.hkx"),
            output_path: PathBuf::from("out/idle.hkx"),
            kind: AnimKind::Standard,
        })
    }

    #[test]
    fn skips_standard_jobs() {
        let jobs = vec![make_standard_job()];
        let config = collect_aa_mods(&jobs);
        assert!(config.is_empty());
    }

    #[test]
    fn skips_unknown_group_names() {
        let jobs = vec![make_fnis_job("xpe", "_unknown_group", 0, 1)];
        let config = collect_aa_mods(&jobs);
        assert!(config.is_empty());
    }

    #[test]
    fn deduplicates_groups_within_mod() {
        // Same group, two animation files → one group entry.
        let jobs = vec![
            make_fnis_job("xpe", "_1hmeqp", 0, 5),
            make_fnis_job("xpe", "_1hmeqp", 1, 5),
        ];
        let config = collect_aa_mods(&jobs);
        assert_eq!(config["xpe"].groups.len(), 1);
    }

    #[test]
    fn base_starts_at_one() {
        let jobs = vec![make_fnis_job("xpe", "_1hmeqp", 0, 5)];
        let mut mods: Vec<AAMod> = collect_aa_mods(&jobs).into_values().collect();
        compute_bases(&mut mods);
        assert_eq!(mods[0].groups[0].base, 1);
    }

    #[test]
    fn base_accumulates_across_mods() {
        // XPMSE: _1hmeqp slot_count=5  → base=1, occupies slots 1-5
        // TestMod: _1hmeqp slot_count=3 → base=6
        let jobs = vec![
            make_fnis_job("xpe", "_1hmeqp", 0, 5),
            make_fnis_job("tst", "_1hmeqp", 0, 3),
        ];
        let mut mods: Vec<AAMod> = collect_aa_mods(&jobs).into_values().collect();
        compute_bases(&mut mods);
        assert_eq!(mods[0].groups[0].base, 1);
        assert_eq!(mods[1].groups[0].base, 6);
    }

    #[test]
    fn crc_changes_on_slot_count_change() {
        let jobs_a = vec![make_fnis_job("xpe", "_1hmeqp", 0, 5)];
        let jobs_b = vec![make_fnis_job("xpe", "_1hmeqp", 0, 3)];

        let mut mods_a: Vec<AAMod> = collect_aa_mods(&jobs_a).into_values().collect();
        let mut mods_b: Vec<AAMod> = collect_aa_mods(&jobs_b).into_values().collect();
        compute_bases(&mut mods_a);
        compute_bases(&mut mods_b);

        assert_ne!(compute_crc(&mods_a), compute_crc(&mods_b));
    }

    #[test]
    fn write_aa_config_smoke() {
        let jobs = vec![
            make_fnis_job("xpe", "_1hmeqp", 0, 5),
            make_fnis_job("xpe", "_dageqp", 0, 6),
            make_fnis_job("xpe", "_sprint", 0, 1),
        ];
        let output_dir = Path::new("../../dummy/debug");
        generate_aa_config_from_jobs(&jobs, output_dir).unwrap();
    }

    // Helper used by tests to inspect intermediate state without file I/O.
    fn collect_aa_mods(jobs: &[AnimIoJob]) -> IndexMap<String, AAMod> {
        let mut aa_mods: IndexMap<String, AAMod> = IndexMap::new();
        for job in jobs {
            let AnimIoJob::Hkx(ConversionJob {
                kind:
                    AnimKind::FnisAA {
                        prefix,
                        group_name,
                        slot_count,
                    },
                ..
            }) = job
            else {
                continue;
            };
            let Some(group_id) = group_id_from_name(group_name) else {
                continue;
            };
            let aa_mod = aa_mods.entry(prefix.clone()).or_insert_with(|| AAMod {
                prefix: prefix.clone(),
                name: prefix.clone(),
                mod_id: 0,
                groups: vec![],
            });
            if !aa_mod.groups.iter().any(|g| g.name == *group_name) {
                aa_mod.groups.push(AAGroup {
                    name: group_name.clone(),
                    group_id,
                    base: 0,
                    slot_count: *slot_count,
                });
            }
        }
        aa_mods
    }

    /// Generates the JSON schema for [`AAConfig`] and writes it to
    /// `schema/aa_config.schema.json`.
    #[cfg(feature = "schema")]
    #[test]
    fn write_schema() {
        let schema = schemars::schema_for!(AAConfig);
        let json = sonic_rs::to_string_pretty(&schema).unwrap();
        std::fs::write("../../tools/schemas/aa_config.schema.json", json).unwrap();
    }
}
