//! Generates the SKSE plugin configuration for FNIS alternate animation variables.
//!
//! Computes per-mod base slot values from load order and produces
//! `aa_config.json` consumed by the fnis_aa SKSE plugin at runtime.
use std::{borrow::Cow, path::Path, sync::Arc};

use indexmap::IndexMap;
use serde::Serialize;

use super::group_names::AAGroupName;
use crate::{
    behaviors::tasks::fnis::patch_gen::io_jobs::{AnimIoJob, AnimKind, ConversionJob},
    errors::Error,
};

/// `(prefix, group_id)` → `base` lookup built from a finalized `AAConfig`.
pub type BaseMap = std::collections::HashMap<(Arc<str>, u64), u64>;

/// Builds the base lookup map from a finalized [`AAConfig`].
///
/// Key: `(prefix, group_id)` — matches the fields in [`FnisAAConfigJob`].
fn build_base_map(config: &AAConfig) -> BaseMap {
    config
        .mods
        .iter()
        .flat_map(|m| {
            m.groups
                .iter()
                .map(|g| ((Arc::clone(&m.prefix), g.name.group_id()), g.base))
        })
        .collect()
}

// =============================================================================
// Data model
// =============================================================================

/// JSON schema URI embedded in every generated `config.json`.
const SCHEMA_URI: &str =
    "https://raw.githubusercontent.com/SARDONYX-sard/d-merge/refs/heads/main/tools/schemas/aa_config.schema.json";

#[derive(Debug, Clone, PartialEq, Hash, Serialize)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub struct AAGroup {
    /// FNIS group identifier.
    ///
    /// Serializes to the FNIS wire string (e.g. `"_1hmeqp"`).
    /// The corresponding `group_id` integer is derived via [`AAGroupName::group_id`].
    pub name: AAGroupName,

    /// First slot index occupied by this mod for this group.
    ///
    /// base 0 is always reserved for vanilla. Custom slots start at 1 and are
    /// assigned contiguously in mod load order:
    /// ```text
    /// slot 0..N     mod A  (base=1, slot_count=N)
    /// slot N+1..M   mod B  (base=N+1, slot_count=M-N)
    /// ```
    pub base: u64,

    #[serde(skip)]
    /// Number of animation styles registered by this mod for this group.
    ///
    /// Determines how many slots this mod occupies starting from `base`.
    ///
    /// It is used to calculate the base of mods with a lower priority than this one.
    pub slot_count: u64,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub struct AAMod {
    /// 3-character mod prefix used by FNIS, e.g. `xpe` for XPMSE.
    ///
    /// Used as the key in `FNIS_aa2::GetAAprefixList()`.
    pub prefix: Arc<str>,

    /// Full mod name, e.g. `XPMSE`.
    ///
    /// Used for logging and debug output only.
    pub name: Arc<str>,

    /// Index of this mod in load order, assigned by d_merge.
    ///
    /// Corresponds to the `PP` component of the `PPGGBB` encoded set string.
    pub mod_id: u64,

    /// Animation groups registered by this mod, sorted by `group_id`.
    pub groups: Vec<AAGroup>,
}

/// Root configuration for the `fnis_aa` SKSE plugin.
///
/// Generated by [d_merge](https://github.com/SARDONYX-sard/d_merge) and read
/// at game startup by `fnis_aa.dll`. Replaces the slot layout that the FNIS
/// generator previously baked into `FNIS_aa2.pex`.
///
/// # File location
/// `SKSE/Plugins/fnis_aa/config.json`
///
/// # Example
/// ```json
/// {
///   "$schema": "https://raw.githubusercontent.com/SARDONYX-sard/fnis_aa/main/schema/aa_config.schema.json",
///   "crc": 123456,
///   "fnis_version": "V07.06.00.0",
///   "mods": [
///     {
///       "prefix": "xpe",
///       "name": "XPMSE",
///       "mod_id": 0,
///       "groups": [
///         { "name": "_1hmeqp", "base": 1, "slot_count": 5 }
///       ]
///     }
///   ]
/// }
/// ```
#[derive(Debug, Serialize)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub struct AAConfig {
    /// URI of the JSON schema for this file.
    ///
    /// Always set to the canonical schema URI. Enables schema validation in
    /// editors such as VS Code.
    #[serde(rename = "$schema")]
    pub schema: Cow<'static, str>,

    /// CRC fingerprint of the current slot layout.
    ///
    /// Computed from mod load order and slot counts. Written to
    /// `FNISaa_crc` on the actor at game load. If the saved value differs,
    /// all animation variables must be re-applied to reflect the new layout.
    pub crc: u32,

    /// FNIS version string returned by `FNISVersionGenerated.get()`.
    ///
    /// e.g. `V07.06.00.0`
    pub fnis_version: Cow<'static, str>,

    /// FNIS version string returned by `fnis.pex`.
    pub fnis_creature_version: Cow<'static, str>,

    /// All mods registered in load order.
    ///
    /// Load order determines `mod_id` assignment and therefore `base` values.
    /// Changing load order produces a different `crc`.
    pub mods: Vec<AAMod>,
}

impl AAConfig {
    /// Creates a new `AAConfig`.
    ///
    /// When the `schema` feature is enabled, the canonical schema URI is
    /// embedded in the output JSON as `$schema`.
    pub fn new(fnis_version: impl Into<Cow<'static, str>>, mods: Vec<AAMod>) -> Self {
        let fnis_version = fnis_version.into();
        Self {
            schema: Cow::Borrowed(SCHEMA_URI),
            crc: compute_crc(&mods),
            fnis_version: fnis_version.clone(),
            fnis_creature_version: fnis_version,
            mods,
        }
    }
}

// =============================================================================
// Base computation
// =============================================================================

/// Assigns `base` and `mod_id` for every group across all mods in load order.
/// Slot 0 is always reserved for vanilla; custom slots start at 1.
fn compute_bases(mods: &mut [AAMod]) {
    let mut next_slot = std::collections::HashMap::new();

    for (mod_id, aa_mod) in mods.iter_mut().enumerate() {
        aa_mod.mod_id = mod_id as u64;
        for group in aa_mod.groups.iter_mut() {
            let slot = next_slot.entry(group.name.group_id()).or_insert(1);
            group.base = *slot;
            *slot += group.slot_count;
        }
    }
}

/// CRC fingerprint of the current slot layout.
/// Any change in load order or slot counts invalidates saved Papyrus values.
fn compute_crc(mods: &[AAMod]) -> u32 {
    use std::hash::{Hash, Hasher};
    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    for aa_mod in mods {
        for group in &aa_mod.groups {
            group.hash(&mut hasher);
        }
    }
    hasher.finish() as u32
}

// =============================================================================
// Output
// =============================================================================

fn write_aa_config(mods: Vec<AAMod>, output_dir: &Path) -> Result<BaseMap, Error> {
    let mut mods = mods;
    compute_bases(&mut mods);
    let config = AAConfig::new("V07.06.00.0", mods);

    let path = output_dir.join("SKSE/Plugins/fnis_aa/config.json");
    let json = sonic_rs::to_string_pretty(&config).map_err(|e| Error::JsonError {
        path: path.clone(),
        source: e,
    })?;
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| Error::FailedIo {
            path: parent.to_path_buf(),
            source: e,
        })?;
    }
    std::fs::write(&path, &json).map_err(|e| Error::FailedIo {
        path: path.clone(),
        source: e,
    })?;

    Ok(build_base_map(&config))
}

// =============================================================================
// Public entry point
// =============================================================================

/// Collects `AAMod` data from a slice of `AnimIoJob` and generates `aa_config.json`.
///
/// Call this once after all `alt_anim_to_oar` jobs have been collected.
/// Load order is preserved via `IndexMap` to ensure a stable CRC.
///
/// # Output path
/// `SKSE/Plugins/fnis_aa/config.json`
pub fn build_aa_config_from_jobs(jobs: &[AnimIoJob], output_dir: &Path) -> Result<BaseMap, Error> {
    // IndexMap preserves insertion order = mod load order, giving a stable CRC.
    let mut aa_mods = IndexMap::new();

    for job in jobs {
        let AnimIoJob::Hkx(ConversionJob {
            kind:
                AnimKind::FnisAA {
                    prefix,
                    group_name,
                    slot_count,
                    ..
                },
            ..
        }) = job
        else {
            continue;
        };

        let aa_mod = aa_mods.entry(Arc::clone(prefix)).or_insert_with(|| AAMod {
            prefix: Arc::clone(prefix),
            name: Arc::clone(prefix),
            mod_id: 0, // assigned later by compute_bases()
            groups: vec![],
        });

        // Each group appears once per mod regardless of how many animation
        // files reference it.
        if !aa_mod.groups.iter().any(|g| g.name == *group_name) {
            aa_mod.groups.push(AAGroup {
                name: *group_name,
                base: 0, // assigned later by compute_bases()
                slot_count: *slot_count,
            });
        }
    }

    write_aa_config(aa_mods.into_values().collect(), output_dir)
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use super::*;

    fn make_fnis_job(
        prefix: &str,
        group_name: AAGroupName,
        slot_index: u64,
        slot_count: u64,
    ) -> AnimIoJob {
        AnimIoJob::Hkx(ConversionJob {
            input_path: PathBuf::from(format!("{prefix}{slot_index}_1hm_equip.hkx")),
            output_path: PathBuf::from("out/1hm_equip.hkx"),
            kind: AnimKind::FnisAA {
                prefix: Arc::from(prefix),
                group_name,
                slot_count,
                is_male_subdir: false,
            },
        })
    }

    fn make_standard_job() -> AnimIoJob {
        AnimIoJob::Hkx(ConversionJob {
            input_path: PathBuf::from("idle.hkx"),
            output_path: PathBuf::from("out/idle.hkx"),
            kind: AnimKind::Standard,
        })
    }

    #[test]
    fn skips_standard_jobs() {
        let jobs = vec![make_standard_job()];
        let config = collect_aa_mods(&jobs);
        assert!(config.is_empty());
    }

    #[test]
    fn deduplicates_groups_within_mod() {
        // Same group, two animation files → one group entry.
        let jobs = vec![
            make_fnis_job("xpe", AAGroupName::OneHmEqp, 0, 5),
            make_fnis_job("xpe", AAGroupName::OneHmEqp, 1, 5),
        ];
        let config = collect_aa_mods(&jobs);
        assert_eq!(config["xpe"].groups.len(), 1);
    }

    #[test]
    fn base_starts_at_one() {
        let jobs = vec![make_fnis_job("xpe", AAGroupName::OneHmEqp, 0, 5)];
        let mut mods: Vec<AAMod> = collect_aa_mods(&jobs).into_values().collect();
        compute_bases(&mut mods);
        assert_eq!(mods[0].groups[0].base, 1);
    }

    #[test]
    fn base_accumulates_across_mods() {
        // XPMSE: _1hmeqp slot_count=5  → base=1, occupies slots 1-5
        // TestMod: _1hmeqp slot_count=3 → base=6
        let jobs = vec![
            make_fnis_job("xpe", AAGroupName::OneHmEqp, 0, 5),
            make_fnis_job("tst", AAGroupName::OneHmEqp, 0, 3),
        ];
        let mut mods: Vec<AAMod> = collect_aa_mods(&jobs).into_values().collect();
        compute_bases(&mut mods);
        assert_eq!(mods[0].groups[0].base, 1);
        assert_eq!(mods[1].groups[0].base, 6);
    }

    #[test]
    fn crc_changes_on_slot_count_change() {
        let jobs_a = vec![make_fnis_job("xpe", AAGroupName::OneHmEqp, 0, 5)];
        let jobs_b = vec![make_fnis_job("xpe", AAGroupName::OneHmEqp, 0, 3)];

        let mut mods_a: Vec<AAMod> = collect_aa_mods(&jobs_a).into_values().collect();
        let mut mods_b: Vec<AAMod> = collect_aa_mods(&jobs_b).into_values().collect();
        compute_bases(&mut mods_a);
        compute_bases(&mut mods_b);

        assert_ne!(&mods_a, &mods_b);
        assert_ne!(compute_crc(&mods_a), compute_crc(&mods_b));
    }

    #[test]
    fn write_aa_config_smoke() {
        let jobs = vec![
            make_fnis_job("xpe", AAGroupName::OneHmEqp, 0, 5),
            make_fnis_job("xpe", AAGroupName::DagEqp, 0, 6),
            make_fnis_job("xpe", AAGroupName::Sprint, 0, 1),
        ];
        let output_dir = Path::new("../../dummy/debug");
        build_aa_config_from_jobs(&jobs, output_dir).unwrap();
    }

    // Helper used by tests to inspect intermediate state without file I/O.
    fn collect_aa_mods(jobs: &[AnimIoJob]) -> IndexMap<Arc<str>, AAMod> {
        let mut aa_mods = IndexMap::new();
        for job in jobs {
            let AnimIoJob::Hkx(ConversionJob {
                kind:
                    AnimKind::FnisAA {
                        prefix,
                        group_name,
                        slot_count,
                        is_male_subdir: false,
                    },
                ..
            }) = job
            else {
                continue;
            };
            let aa_mod = aa_mods.entry(Arc::clone(prefix)).or_insert_with(|| AAMod {
                prefix: Arc::clone(prefix),
                name: Arc::clone(prefix),
                mod_id: 0,
                groups: vec![],
            });
            if !aa_mod.groups.iter().any(|g| g.name == *group_name) {
                aa_mod.groups.push(AAGroup {
                    name: *group_name,
                    base: 0,
                    slot_count: *slot_count,
                });
            }
        }
        aa_mods
    }

    /// Generates the JSON schema for [`AAConfig`] and writes it to
    /// `schema/aa_config.schema.json`.
    #[cfg(feature = "schema")]
    #[test]
    fn write_schema() {
        let schema = schemars::schema_for!(AAConfig);
        let json = sonic_rs::to_string_pretty(&schema).unwrap();
        std::fs::write("../../tools/schemas/aa_config.schema.json", json).unwrap();
    }
}
