//! # Dummy ESP Generator

use std::ffi::CStr;

use skyrim_esp::{Config, Version};

/// Write a minimal FNIS dummy ESP to `<output_dir>/FNIS.esp`.
///
/// Creates `output_dir` (and any missing parents) if it does not exist.
/// Uses [`BufWriter`] to batch small writes into fewer system_calls.
///
/// [`BufWriter`]: std::io::BufWriter
pub(super) fn save_dummy_esp<P>(output_dir: P, target: crate::OutPutTarget) -> std::io::Result<()>
where
    P: AsRef<std::path::Path>,
{
    let output_dir = output_dir.as_ref();

    // https://en.uesp.net/wiki/Skyrim_Mod:Mod_File_Format/TES4
    let version = match target {
        crate::OutPutTarget::SkyrimSe => Version::Form44,
        crate::OutPutTarget::SkyrimLe => Version::Form43,
    };

    const AUTHOR: &CStr = c"SARDONYX";
    const DESCRIPTION: &CStr = c"FNIS dummy esp generated by d_merge.";

    let config = Config {
        version,
        author: Some(AUTHOR),
        description: Some(DESCRIPTION),
    };

    // 511 bytes check
    const {
        assert!(
            AUTHOR.to_bytes_with_nul().len() <= 512,
            "Author string must be at most 511 bytes + null terminator"
        );
        assert!(
            DESCRIPTION.to_bytes_with_nul().len() <= 512,
            "Description string must be at most 511 bytes + null terminator"
        );
    }

    std::fs::create_dir_all(output_dir)?;

    let file = std::fs::File::create(output_dir.join("FNIS.esp"))?;
    let mut w = std::io::BufWriter::new(file);
    skyrim_esp::write_dummy_esp(&mut w, &config)?;
    std::io::Write::flush(&mut w)
}
