use std::{fs::File, io::Write, path::Path};

struct Config<'a> {
    version: f32,
    author: Option<&'a str>,
    description: Option<&'a str>,
}

fn zstring(s: &str) -> Vec<u8> {
    let mut v = s.as_bytes().to_vec();
    v.push(0); // null terminator
    v
}

fn subrecord(name: &str, data: &[u8]) -> Vec<u8> {
    let mut v = Vec::new();

    v.extend_from_slice(name.as_bytes()); // 4 bytes
    v.extend_from_slice(&(data.len() as u16).to_le_bytes()); // size
    v.extend_from_slice(data);

    v
}

fn create_dummy_esp(config: &Config) -> Vec<u8> {
    let mut body = Vec::new();

    // --- HEDR ---
    let mut hedr_data = Vec::new();
    hedr_data.extend_from_slice(&config.version.to_le_bytes()); // f32
    hedr_data.extend_from_slice(&0_u32.to_le_bytes()); // num records
    hedr_data.extend_from_slice(&0x800_u32.to_le_bytes()); // next object ID

    body.extend(subrecord("HEDR", &hedr_data));

    // --- CNAM ---
    if let Some(author) = config.author {
        body.extend(subrecord("CNAM", &zstring(author)));
    }

    // --- SNAM ---
    if let Some(desc) = config.description {
        body.extend(subrecord("SNAM", &zstring(desc)));
    }

    // --- TES4 Header ---
    let mut result = Vec::new();

    result.extend_from_slice(b"TES4"); // type
    result.extend_from_slice(&(body.len() as u32).to_le_bytes()); // size
    result.extend_from_slice(&0_u32.to_le_bytes()); // flags
    result.extend_from_slice(&0_u32.to_le_bytes()); // formID
    result.extend_from_slice(&0_u32.to_le_bytes()); // timestamp
    result.extend_from_slice(&0_u32.to_le_bytes()); // version control

    result.extend(body);

    result
}

pub(super) fn save_dummy_esp(output_dir: &Path) -> std::io::Result<()> {
    let config = Config {
        version: 1.0,
        author: Some("SARDONYX"),
        description: Some("FNIS dummy esp generated by d_merge."),
    };
    let path = output_dir.join("FNIS.esp");

    std::fs::create_dir_all(output_dir)?;
    let data = create_dummy_esp(&config);
    let mut file = File::create(path)?;
    file.write_all(&data)?;
    Ok(())
}
