pub(super) mod aliases;
mod apply_patches;
pub(super) mod behavior_gen;
mod collect_templates_and_patches;
pub mod config;
mod hkx_files_gen;
mod merge_patches;
mod results;
pub(super) mod tables;
pub(super) mod write_errors;
