---
name: Bug Report
description: File a bug report
title: '[Bug]: '
labels: ['bug']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Before submitting, please check whether your issue has already been reported:
        [Search existing issues](https://github.com/SARDONYX-sard/d-merge/issues?q=is%3Aissue)

        Please note that patcher-related issues can be inherently difficult to diagnose,
        as they depend on factors such as your load order and the combination of active patches.

        The key factor that determines how likely I can fix a bug is **how easily the cause can be narrowed down**.
        In other words, the fewer mods and patches involved, the higher the chance of identifying the root cause.

        Approximate likelihood of resolving an issue:

        - ✅ **High (≈80-100%)** — The issue always occurs with one specific mod (and its dependencies).
        - ⚠️ **Medium (≈40-70%)** — The issue consistently occurs when certain specific mods are active,
          but involves multiple patches, making it harder to isolate.
        - ❌ **Low (≈0-30%)** — The report is based on a large or unclear setup with many active patches,
          and cannot be reproduced in a simplified environment.
          In such cases, fixing the issue is often very difficult.

        Even if the problem involves only one mod, a large number of generated patches
        can still make root-cause analysis challenging.

  # Software Version
  - type: input
    id: version
    attributes:
      label: D Merge Version
      description: What version of our software are you running?
      placeholder: 0.1.0-beta.3
    validations:
      required: true

  # CPU
  - type: input
    id: cpu
    attributes:
      label: CPU brand
      description: Enter your CPU model
      placeholder: 'Intel(R) Core(TM) i7-8700'
    validations:
      required: false

  # DRAM
  - type: input
    id: dram
    attributes:
      label: DRAM
      description: Enter your total DRAM
      placeholder: '32 GB'
    validations:
      required: false

  # GPU
  - type: input
    id: gpu
    attributes:
      label: GPU
      description: Enter your graphics card
      placeholder: 'NVIDIA GeForce GTX 1080 Ti'
    validations:
      required: false

  # OS
  - type: input
    id: os
    attributes:
      label: Operating System
      description: Enter your OS edition, version, and build (e.g., Windows 11 24H2 build 26100.6584)
      placeholder: 'Windows 11 24H2 build 26100.6584'
    validations:
      required: true

  # Skyrim Version
  - type: dropdown
    id: skyrim-edition
    attributes:
      label: Skyrim Edition
      description: Enter your SkyrimEdition
      options:
        - Special/Anniversary Edition(64bit)
        - VR(64bit)
        - Legendary Edition(32bit)
    validations:
      required: true

  - type: input
    id: skyrim-version
    attributes:
      label: Skyrim Version
      description: Enter your Skyrim Special Edition version
      placeholder: '1.6.1170.0'
    validations:
      required: true

  # Unexpected behavior
  - type: textarea
    id: unexpected-behavior
    attributes:
      label: Unexpected behavior
      description: Describe the behavior that is not working as expected.
      placeholder: |
        Example:
          FNIS Flyer SE(v7.0) can perform animations but cannot move.
    validations:
      required: true

  # Reproduction steps
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: |
        Describe step by step how to reproduce the issue.
        (It's difficult to find the problem if it can't be reproduced.)
      placeholder: |
        1. Start the game with only FNIS Flyer SE(v7.0) enabled
        2. Perform action X
        3. Observe unexpected behavior'
    validations:
      required: true

  # Debug / Log output
  - type: textarea
    id: debug-output
    attributes:
      label: Debug / Log Output
      description: |
        Include relevant logs. Check `<output dir>/.d_merge/logs/`, `<output dir>/.d_merge/debug/` if applicable.
      placeholder: |
        Copy from
        - `<output dir>/.d_merge/logs/`
        - <output dir>/.d_merge/debug/
      # We don't use `render: Shell` because it doesn't allow me to place files.
