name: FFI Node.js

on:
  # TODO: We will consider optimizing it if there is demand
  # push:
  #   branches: ["main"]
  #   paths-ignore:
  #     - "**/*.md"
  # pull_request:
  #   branches: ["*"]
  #   paths-ignore:
  #     - "**/*.md"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v6.0.2
        with:
          submodules: true

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
      - name: Rust cache
        uses: Swatinem/rust-cache@v2.9.1
        with:
          prefix-key: cargo-${{ matrix.platform }}-ffi-node
      - name: Sync node version and setup cache
        uses: actions/setup-node@v6.3.0
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Build Node FFI
        run: |
          npm ci -w ffi/javascript/node
          cd ffi/javascript/node
          npm run build

      - name: Upload FFI artifact
        uses: actions/upload-artifact@v7
        with:
          name: d_merge_ffi_node_${{ matrix.platform }}
          path: |
            ffi/javascript/node/index.js
            ffi/javascript/node/index.d.ts
            ffi/javascript/node/package.json
            ffi/javascript/node/*.node
