name: FFI Node.js

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  windows:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
      - name: Rust cache
        uses: Swatinem/rust-cache@v2.7.8
        with:
          prefix-key: cargo-${{ matrix.platform }}-ffi-node
      - name: Sync node version and setup cache
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Build Node FFI
        run: |
          npm ci -w ffi/javascript/node
          cd ffi/javascript/node
          npm run build

      - name: Upload FFI artifact
        uses: actions/upload-artifact@v4
        with:
          name: d_merge_ffi_node_${{ matrix.platform }}
          path: |
            ffi/javascript/node/index.js
            ffi/javascript/node/index.d.ts
            ffi/javascript/node/package.json
            ffi/javascript/node/*.node
