name: Release GUI

on:
  push:
    tags:
      - "*"

env:
  APP_NAME: d_merge
  BUILD_PROFILE: release

jobs:
  build:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          # --------------------
          # Tauri
          # --------------------
          - target: aarch64-apple-darwin
            os: macos-latest
            kind: tauri
            art_name: d_merge-tauri-aarch64-apple-darwin

          - target: x86_64-pc-windows-msvc
            os: windows-latest
            kind: tauri
            art_name: d_merge-tauri-x86_64-pc-windows-msvc

          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            kind: tauri
            art_name: d_merge-tauri-x86_64-unknown-linux-gnu

          # --------------------
          # egui
          # --------------------
          - target: aarch64-apple-darwin
            os: macos-latest
            kind: egui
            art_name: d_merge-egui-aarch64-apple-darwin

          - target: x86_64-pc-windows-msvc
            os: windows-latest
            kind: egui
            art_name: d_merge-egui-x86_64-pc-windows-msvc

          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            kind: egui
            art_name: d_merge-egui-x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup
        uses: ./.github/actions/setup-deps
        with:
          platform: ${{ matrix.os }}
          build_profile: ${{ env.BUILD_PROFILE }}
          install_front_deps: ${{ matrix.kind == 'tauri' && 'true' || 'false' }}

      # ----------------------------
      # build switch
      # ----------------------------
      - name: Build GUI (tauri)
        if: matrix.kind == 'tauri'
        run: npm run build:${{ env.BUILD_PROFILE }}

      - name: Build GUI (egui)
        if: matrix.kind == 'egui'
        run: cargo build -p d_merge_egui --profile ${{ env.BUILD_PROFILE }}

      # ----------------------------
      # move output (existing logic)
      # ----------------------------
      - name: Move exe -> ./build
        uses: ./.github/actions/setup-release
        with:
          app_name: ${{ matrix.kind == 'tauri' && 'd_merge' || 'd_merge_egui' }}
          build_profile: ${{ env.BUILD_PROFILE }}

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.art_name }}
          # to include .keep file
          include-hidden-files: true
          path: |
            ./build/

  # --------------------------------------------------------------------------------------------------------------------
  translations:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Build translations artifact
        shell: bash
        run: |
          mkdir -p build

          for file in locales/egui/*/translation.json; do
            lang=$(basename "$(dirname "$file")")

            mkdir -p "build/$lang/.d_merge"
            cp "$file" "build/$lang/.d_merge/translation.json"
          done

      - name: Upload translations
        uses: actions/upload-artifact@v7
        with:
          name: translations
          include-hidden-files: true
          path: build/

  # --------------------------------------------------------------------------------------------------------------------
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          skip-decompress: true
          path: dist

      # --------------------
      # changelog
      # --------------------
      - name: Generate changelog
        id: changelog
        uses: requarks/changelog-action@v1.10.3
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      # --------------------
      # release
      # --------------------
      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cat > release_notes.md <<'EOF'
          ${{ steps.changelog.outputs.changes }}
          EOF

          gh release create "${{ github.ref_name }}" dist/**/*.zip \
            --title "${{ env.APP_NAME }} v${{ github.ref_name }}" \
            --notes-file release_notes.md

      # --------------------
      # commit changelog
      # --------------------
      - name: Commit CHANGELOG.md
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin
          git checkout main
          git pull origin main

          git add CHANGELOG.md
          git commit -m "docs: update CHANGELOG for ${{ github.ref_name }}" || exit 0
          git push origin main
